### ISSUE TITLE
Feature Request: Support for mixed content

### ISSUE THREAD

**Issue by SebastianStehle** [ikorin24/U8XmlParser#19]
Afaik the normal xml is totally valid.

```
<div>
<strong>Hello</strong> U8XMLParser
</div>
```

But in this case I have no idea how to get the inner xml.

* InnerText is empty.
* AsRawXml returns everything including the div
* Looping over XmlNodes returns only the strong node, but not a text node or so.

**Comment by ikorin24** [comment]
Thank you for the report.

I did not consider nodes that have both nodes and text in their child elements.
The parser implementation needs to be corrected.

**Comment by SebastianStehle** [comment]
Great work btw. As I said in the other issue we are working on a MJML port and this library gives us a 20% performance speed. OR would give us...

**Comment by SebastianStehle** [comment]
Btw: Do you also support comments?

**Comment by SebastianStehle** [comment]
I have special "raw" nodes and for these raw nodes I just need to print the output directly. Something like

```
<mj-raw>
  <!-- Comment -->
  <hr /> 
  Foobar
</mj-raw>
```

If I can somehow get the inner content it works fine for me.

**Comment by ikorin24** [comment]
Try out the following code.
```cs
XmlNode mj_raw = ...;  // <mj-raw> node
RawString str = mj_raw.AsRawString();
Console.WriteLine(str);
```

The output is

```
<mj-raw>
  <!-- Comment -->
  <hr /> 
  Foobar
</mj-raw>
```

Is this what you want ?

If you want to get the content of `mj-raw` node, you should slice the `RawString`.

**Comment by SebastianStehle** [comment]
Awesome :)
