### ISSUE TITLE
FormatException should contain detailed error message.

### ISSUE THREAD

**Issue by SebastianStehle** [ikorin24/U8XmlParser#22]
Your example was just throwing FormatException

There is a question mark missing and you just get a FormatException without any explanation. It is hard to find issues like that.

```
<?xml version="1.0" encoding="UTF-8"> 
<SomeData>
    <Data aa="20">bbb</Data>
    <Data aa="30">ccc</Data>
</SomeData>
```

**Comment by ikorin24** [comment]
Is the output of row and column numbers intended to be displayed as error messages? ( cf. your another issue ( #18 ) )

**Comment by SebastianStehle** [comment]
This would make it even better
