### ISSUE TITLE
XML parser accepts invalid entities

### ISSUE THREAD

**Issue by SebastianStehle** [ikorin24/U8XmlParser#23]
According to the XML specs entities need to be registered, e.g. this is not valid XML:

```
<?xml version="1.0" encoding="UTF-8"?>
<SomeData>
	<Data>&copy;</Data>
</SomeData>
```

You have to register these entities:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SomeData[
	<!ENTITY copy "&#169;;">
]>
<SomeData>
	<Data>&copy;</Data>
</SomeData>
```

**Comment by ikorin24** [comment]
U8XmlParser is designed to read all correct xml, but it is not designed to always output an error for wrong xml. This design is for speed of execution and will not be changed in the future.

If you need proper handling of wrong xml, we recommend you to use other parsers.
