### ISSUE TITLE
Ampersand is not allowed in Xml attributes

### ISSUE THREAD

**Issue by SebastianStehle** [ikorin24/U8XmlParser#25]
This is just another example for an invalid XML that is accepted by this library:

```
<?xml version="1.0" encoding="UTF-8"?>
<SomeData>
	<Foo url="http://google.com?quer1=1&query2=2"></Foo>
</SomeData>
```

**Comment by ikorin24** [comment]
U8XmlParser is designed to read all correct xml, but it is not designed to always output an error for wrong xml. This design is for speed of execution and will not be changed in the future.

If you need proper handling of wrong xml, we recommend you to use other parsers.

(Sorry for repeating my response to other issues)

**Comment by SebastianStehle** [comment]
Thats fine, I just wanted to have your opinion / position about that. We have to cleanup broken XML anyway and it would our live easier if the xml parser is not so strict.
